version: "3.8"

services:
  db:
    image: postgres:17.2
    restart: always
    container_name: quests_postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: quests
    ports:
      - 5432:5432

volumes:
  db-data:
